import type { OutreachDetail, Prospect, ProspectDetail } from "@/lib/api";

// Entirely fictional prospects for the Demo Workspace. Names, emails, and
// LinkedIn URLs are all invented (note the "-demo" LinkedIn slugs) and do
// not correspond to real people.

function emailOutreach(
  maturity: string,
  reachedOutAt: string | null,
  respondedAt: string | null,
  interactions: OutreachDetail["interactions"] = [],
): OutreachDetail {
  return {
    maturity,
    last_contact_date: reachedOutAt,
    next_followup_date: null,
    reached_out_at: reachedOutAt,
    responded_at: respondedAt,
    interactions,
  };
}

export const DEMO_PROSPECTS: Prospect[] = [
  {
    id: "demo-prospect-1",
    name: "Priya Nair",
    title: "Director of Engineering",
    seniority: "director",
    company_name: "NimbusData",
    email: "priya.nair@nimbusdata-demo.io",
    email_status: "verified",
    linkedin_url: "https://linkedin.com/in/priya-nair-demo",
    city: "Austin",
    state: "TX",
    country: "United States",
    icp_names: ["Series B SaaS — VP Eng"],
    email_outreach: {
      maturity: "meeting_booked",
      last_contact_date: "2026-08-28T14:00:00Z",
      next_followup_date: null,
    },
    linkedin_outreach: {
      maturity: "meeting_booked",
      last_contact_date: "2026-08-27T10:00:00Z",
      next_followup_date: null,
    },
    created_at: "2026-08-16T09:00:00Z",
    updated_at: "2026-08-28T14:00:00Z",
  },
  {
    id: "demo-prospect-2",
    name: "Jordan Lee",
    title: "VP Engineering",
    seniority: "vp",
    company_name: "Acme Corp",
    email: "jordan.lee@acme-corp-demo.com",
    email_status: "verified",
    linkedin_url: "https://linkedin.com/in/jordan-lee-demo",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    icp_names: ["Series B SaaS — VP Eng"],
    email_outreach: {
      maturity: "in_conversation",
      last_contact_date: "2026-09-01T11:00:00Z",
      next_followup_date: "2026-09-05T11:00:00Z",
    },
    linkedin_outreach: null,
    created_at: "2026-08-17T09:00:00Z",
    updated_at: "2026-09-01T11:00:00Z",
  },
  {
    id: "demo-prospect-3",
    name: "Marcus Chen",
    title: "Head of Platform",
    seniority: "head",
    company_name: "Vantage Cloud",
    email: "marcus.chen@vantagecloud-demo.io",
    email_status: "verified",
    linkedin_url: "https://linkedin.com/in/marcus-chen-demo",
    city: "Denver",
    state: "CO",
    country: "United States",
    icp_names: ["Series B SaaS — VP Eng"],
    email_outreach: null,
    linkedin_outreach: null,
    created_at: "2026-08-30T09:00:00Z",
    updated_at: "2026-08-30T09:00:00Z",
  },
  {
    id: "demo-prospect-4",
    name: "Sam Osei",
    title: "Director of Compliance",
    seniority: "director",
    company_name: "Kestrel Fintech",
    email: "sam.osei@kestrelfintech-demo.com",
    email_status: "verified",
    linkedin_url: "https://linkedin.com/in/sam-osei-demo",
    city: "London",
    state: null,
    country: "United Kingdom",
    icp_names: ["Fintech Compliance Leads"],
    email_outreach: {
      maturity: "responded_no",
      last_contact_date: "2026-08-25T09:00:00Z",
      next_followup_date: null,
    },
    linkedin_outreach: null,
    created_at: "2026-08-18T09:00:00Z",
    updated_at: "2026-08-25T09:00:00Z",
  },
  {
    id: "demo-prospect-5",
    name: "Aisha Rahman",
    title: "CFO",
    seniority: "c_suite",
    company_name: "Ledger Trust",
    email: "aisha.rahman@ledgertrust-demo.io",
    email_status: "verified",
    linkedin_url: "https://linkedin.com/in/aisha-rahman-demo",
    city: "Dublin",
    state: null,
    country: "Ireland",
    icp_names: ["Fintech Compliance Leads"],
    email_outreach: {
      maturity: "responded_yes",
      last_contact_date: "2026-09-02T09:00:00Z",
      next_followup_date: "2026-09-06T09:00:00Z",
    },
    linkedin_outreach: null,
    created_at: "2026-08-19T09:00:00Z",
    updated_at: "2026-09-02T09:00:00Z",
  },
  {
    id: "demo-prospect-6",
    name: "Elena Petrov",
    title: "VP Operations",
    seniority: "vp",
    company_name: "Bright Health Ops",
    email: "elena.petrov@brighthealthops-demo.com",
    email_status: "verified",
    linkedin_url: "https://linkedin.com/in/elena-petrov-demo",
    city: "Chicago",
    state: "IL",
    country: "United States",
    icp_names: ["Healthcare Ops Directors"],
    email_outreach: {
      maturity: "sent",
      last_contact_date: "2026-09-03T09:00:00Z",
      next_followup_date: "2026-09-10T09:00:00Z",
    },
    linkedin_outreach: null,
    created_at: "2026-08-20T09:00:00Z",
    updated_at: "2026-09-03T09:00:00Z",
  },
];

export const DEMO_PROSPECT_DETAILS: Record<string, ProspectDetail> = {
  "demo-prospect-1": {
    id: "demo-prospect-1",
    name: "Priya Nair",
    title: "Director of Engineering",
    seniority: "director",
    email: "priya.nair@nimbusdata-demo.io",
    email_status: "verified",
    direct_phone: null,
    linkedin_url: "https://linkedin.com/in/priya-nair-demo",
    city: "Austin",
    state: "TX",
    country: "United States",
    company_name: "NimbusData",
    company_domain: "nimbusdata-demo.io",
    company_linkedin_url: "https://linkedin.com/company/nimbusdata-demo",
    email_outreach: emailOutreach(
      "meeting_booked",
      "2026-08-26T14:00:00Z",
      "2026-08-27T09:00:00Z",
      [
        {
          timestamp: "2026-08-26T14:00:00Z",
          direction: "outbound",
          content:
            "Introduced our platform and asked for 15 minutes this week.",
        },
        {
          timestamp: "2026-08-27T09:00:00Z",
          direction: "inbound",
          content: "Sounds interesting — let's grab time Thursday.",
        },
        {
          timestamp: "2026-08-28T14:00:00Z",
          direction: "outbound",
          content: "Meeting booked for Sept 4 at 10am.",
        },
      ],
    ),
    linkedin_outreach: emailOutreach(
      "meeting_booked",
      "2026-08-25T10:00:00Z",
      "2026-08-27T10:00:00Z",
    ),
  },
  "demo-prospect-2": {
    id: "demo-prospect-2",
    name: "Jordan Lee",
    title: "VP Engineering",
    seniority: "vp",
    email: "jordan.lee@acme-corp-demo.com",
    email_status: "verified",
    direct_phone: null,
    linkedin_url: "https://linkedin.com/in/jordan-lee-demo",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    company_name: "Acme Corp",
    company_domain: "acme-corp-demo.com",
    company_linkedin_url: "https://linkedin.com/company/acme-corp-demo",
    email_outreach: emailOutreach(
      "in_conversation",
      "2026-08-29T11:00:00Z",
      "2026-09-01T11:00:00Z",
      [
        {
          timestamp: "2026-08-29T11:00:00Z",
          direction: "outbound",
          content: "Reached out about scaling engineering headcount.",
        },
        {
          timestamp: "2026-09-01T11:00:00Z",
          direction: "inbound",
          content: "Flagged for review — asked for pricing details.",
        },
      ],
    ),
    linkedin_outreach: null,
  },
};
