import type { Company } from "@/lib/api";

// Entirely fictional companies for the Demo Workspace. None of these names,
// domains, or LinkedIn URLs correspond to real organizations.
export const DEMO_COMPANIES: Company[] = [
  {
    id: "demo-company-1",
    name: "NimbusData",
    domain: "nimbusdata-demo.io",
    linkedin_url: "https://linkedin.com/company/nimbusdata-demo",
    employee_range: "50-200",
    revenue_range: "$10M-$50M",
    founded_year: 2018,
    icp_names: ["Series B SaaS — VP Eng"],
    prospects_count: 2,
    created_at: "2026-08-10T09:00:00Z",
  },
  {
    id: "demo-company-2",
    name: "Acme Corp",
    domain: "acme-corp-demo.com",
    linkedin_url: "https://linkedin.com/company/acme-corp-demo",
    employee_range: "200-500",
    revenue_range: "$50M-$100M",
    founded_year: 2015,
    icp_names: ["Series B SaaS — VP Eng"],
    prospects_count: 1,
    created_at: "2026-08-11T09:00:00Z",
  },
  {
    id: "demo-company-3",
    name: "Vantage Cloud",
    domain: "vantagecloud-demo.io",
    linkedin_url: "https://linkedin.com/company/vantagecloud-demo",
    employee_range: "50-200",
    revenue_range: "$10M-$50M",
    founded_year: 2019,
    icp_names: ["Series B SaaS — VP Eng"],
    prospects_count: 1,
    created_at: "2026-08-12T09:00:00Z",
  },
  {
    id: "demo-company-4",
    name: "Kestrel Fintech",
    domain: "kestrelfintech-demo.com",
    linkedin_url: "https://linkedin.com/company/kestrelfintech-demo",
    employee_range: "200-1000",
    revenue_range: "$100M-$500M",
    founded_year: 2012,
    icp_names: ["Fintech Compliance Leads"],
    prospects_count: 1,
    created_at: "2026-08-13T09:00:00Z",
  },
  {
    id: "demo-company-5",
    name: "Ledger Trust",
    domain: "ledgertrust-demo.io",
    linkedin_url: "https://linkedin.com/company/ledgertrust-demo",
    employee_range: "200-1000",
    revenue_range: "$100M-$500M",
    founded_year: 2010,
    icp_names: ["Fintech Compliance Leads"],
    prospects_count: 1,
    created_at: "2026-08-14T09:00:00Z",
  },
  {
    id: "demo-company-6",
    name: "Bright Health Ops",
    domain: "brighthealthops-demo.com",
    linkedin_url: "https://linkedin.com/company/brighthealthops-demo",
    employee_range: "100-1000",
    revenue_range: "$50M-$100M",
    founded_year: 2016,
    icp_names: ["Healthcare Ops Directors"],
    prospects_count: 1,
    created_at: "2026-08-15T09:00:00Z",
  },
];
